#!/bin/bash

set -o errexit -o nounset -o pipefail

install_deps() {
  for version in 2 3;
  do
    python$version -m pip install .
  done
}

install_extensions() {
    cd test/extensions
    sh install_packages.sh
    cd ../../
}

install_user_extensions() {
    local args=("$@")
    local i=0
    while [ $i -lt ${#args[@]} ]; do
        if [ "${args[$i]}" = "--extension" ] && [ $((i + 1)) -lt ${#args[@]} ]; then
            local ext_path="${args[$((i + 1))]}"
            if [ -f "$ext_path/setup.py" ] || [ -f "$ext_path/pyproject.toml" ]; then
                echo "Installing extension from $ext_path"
                pip install -e "$ext_path"
            fi
        fi
        i=$((i + 1))
    done
}

run_tests() {
  cd test/core && PYTHONPATH=`pwd`/../../ python3 run_tests.py --num-parallel 8 "$@" && cd ../../
}

# We run realtime cards tests separately because there these tests validate the asynchronous updates to the
# information stored in the datastore. So if there are other processes starving resources then these tests will
# surely fail since a lot of checks have timeouts. 
run_runtime_card_tests() {
  CARD_GRAPHS="small-foreach,small-parallel,nested-branches,single-linear-step,simple-foreach"
  cd test/core && PYTHONPATH=`pwd`/../../ python3 run_tests.py --num-parallel 8 --contexts python3-all-local-cards-realtime --graphs $CARD_GRAPHS && cd ../../
}

install_deps && install_extensions && install_user_extensions "$@" && run_tests "$@" && run_runtime_card_tests
